### ISSUE TITLE
undefined method `before' for nil:NilClass 

### ISSUE THREAD

**Issue by yegor256** [yegor256/xcop#33]
```
Traceback (most recent call last):
	10: from /Users/yegor/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `<main>'
	 9: from /Users/yegor/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `eval'
	 8: from /Users/yegor/.rvm/gems/ruby-2.7.0/bin/xcop:23:in `<main>'
	 7: from /Users/yegor/.rvm/gems/ruby-2.7.0/bin/xcop:23:in `load'
	 6: from /Users/yegor/.rvm/gems/ruby-2.7.0/gems/xcop-0.7.1/bin/xcop:94:in `<top (required)>'
	 5: from /Users/yegor/.rvm/gems/ruby-2.7.0/gems/xcop-0.7.1/lib/xcop/cli.rb:59:in `fix'
	 4: from /Users/yegor/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/set.rb:328:in `each'
	 3: from /Users/yegor/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/set.rb:328:in `each_key'
	 2: from /Users/yegor/.rvm/gems/ruby-2.7.0/gems/xcop-0.7.1/lib/xcop/cli.rb:60:in `block in fix'
	 1: from /Users/yegor/.rvm/gems/ruby-2.7.0/gems/xcop-0.7.1/lib/xcop/document.rb:59:in `fix'
/lib/nokogiri/xml/node_set.rb:63:in `before': undefined method `before' for nil:NilClass (NoMethodError)
```

**Comment by bibonix** [comment]
I am planning to work on this issue. I will start by reproducing the failure and then propose a fix.

**Comment by bibonix** [comment]
I investigated this issue against the current `master` branch and have findings to share.

## Original Bug

The traceback in the issue is from `xcop-0.7.1`, where `lib/xcop/document.rb:59` was:

```ruby
xml.children.before(
  Nokogiri::XML::Comment.new(xml, "\n#{license.strip}\n")
)
```

This was inside the old `Document#fix(license)` method (used by `xcop --fix --license=...`). When the input file had no element children at the document root after `xml.xpath('/comment()').remove` (e.g. an XML containing only a comment, or an XML with just the `<?xml ... ?>` declaration), `xml.children` was an empty `Nokogiri::XML::NodeSet`. Calling `.before(node)` on an empty NodeSet delegates to `first.before(...)`, where `first` returns `nil`, hence the `NoMethodError: undefined method 'before' for nil:NilClass`.

## Reproduction (confirms original bug)

Using the v0.7.1 code path:

```ruby
xml = Nokogiri::XML(File.open('comment_only.xml'), &:noblanks) # file is `<?xml version="1.0"?>\n<!-- license -->`
xml.xpath('/comment()').remove
xml.children.before(Nokogiri::XML::Comment.new(xml, "\nNew License\n"))
# => NoMethodError: undefined method `before' for nil
```

I reproduced this locally with two inputs that fail in the v0.7.1 logic:
- `<?xml version="1.0"?>\n<!-- license -->` (comment only)
- `<?xml version="1.0"?>` (empty XML)

## Current Status (no longer reproducible)

This bug is no longer reachable on `master`:

1. `Document#fix` no longer takes a `license` parameter. It is now simply:

   ```ruby
   def fix
     File.write(@path, ideal)
   end
   ```

2. The `--license` CLI flag is documented as `'This option is deprecated'` in `bin/xcop` and is not passed to `Document#fix` anywhere.
3. There are no calls to `.before(` left in `lib/` or `test/` — `grep -rn '\.before(' lib/ test/` returns nothing.

I also exercised `Xcop::Document.new(f).fix` against several edge-case inputs (empty XML, comment-only XML, DOCTYPE-only, XHTML, etc.) and none of them raise — the `fix` method completes cleanly and writes the canonical form.

## Suggestion

The original failing code path no longer exists, and the use case (`xcop --fix --license=...`) is gone. I'd suggest closing this issue as resolved. I'll leave the close action to the maintainers.
