### ISSUE TITLE
Could not find 'racc' (~> 1.4) 

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/xcop#40]
I use `xcop` through `maven-antrun-plugin`. To be clear I use `jcabi-parent` which has the following definition of `xcop`:
```xml
<plugin>
  <artifactId>maven-antrun-plugin</artifactId>
  <version>3.1.0</version>
  <executions>
    <execution>
      <phase>verify</phase>
      <id>jcabi-xcop</id>
      <configuration>
        <target>
          <taskdef resource="net/sf/antcontrib/antcontrib.properties" classpathref="maven.plugin.classpath"/>
          <property environment="env"/>
          <available file="xcop" filepath="${env.PATH}" property="xcop.present"/>
          <if>
            <equals arg1="${xcop.present}" arg2="true"/>
            <then>
              <patternset id="xcop.main">
                <include name="**/*.xml"/>
                <include name="**/*.xsl"/>
                <include name="**/*.xsd"/>
                <exclude name="**/target/**/*"/>
                <exclude name=".idea/**/*"/>
              </patternset>
              <condition property="xcop.excludes.defined">
                <isreference refid="xcop.excludes"/>
              </condition>
              <if>
                <equals arg1="${xcop.excludes.defined}" arg2="true"/>
                <then>
                  <fileset dir="." id="files">
                    <patternset refid="xcop.main"/>
                    <patternset refid="xcop.excludes"/>
                  </fileset>
                  <pathconvert refid="files" property="converted" pathsep=" "/>
                </then>
                <else>
                  <fileset dir="." id="files">
                    <patternset refid="xcop.main"/>
                  </fileset>
                  <pathconvert refid="files" property="converted" pathsep=" "/>
                </else>
              </if>
              <condition property="os.windows">
                <os family="windows"/>
              </condition>
              <if>
                <equals arg1="${os.windows}" arg2="true"/>
                <then>
                  <exec executable="cmd" failonerror="true">
                    <arg line="/c xcop"/>
                    <arg value="--license"/>
                    <arg value="LICENSE.txt"/>
                    <arg line="${converted}"/>
                  </exec>
                </then>
                <else>
                  <exec executable="xcop" failonerror="true">
                    <arg value="--license"/>
                    <arg value="LICENSE.txt"/>
                    <arg line="${converted}"/>
                  </exec>
                </else>
              </if>
            </then>
            <else>
              <echo message="XCOP is not available in PATH"/>
            </else>
          </if>
        </target>
      </configuration>
      <goals>
        <goal>run</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

When I run `mvn clean install`, I get the following output:
```
[INFO] --- antrun:3.1.0:run (jcabi-xcop) @ jeo-maven-plugin ---
[INFO] Executing tasks
[INFO]      [exec] /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'racc' (~> 1.4) among 116 total gem(s) (Gem::MissingSpecError)
[INFO]      [exec] Checked in 'GEM_PATH=/Users/lombrozo/.gem/ruby/3.1.3:/Users/lombrozo/.rubies/ruby-3.1.3/lib/ruby/gems/3.1.0', execute `gem env` for more information
[INFO]      [exec]      from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
[INFO]      [exec]      from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
[INFO]      [exec]      from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
[INFO]      [exec]      from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
[INFO]      [exec]      from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
[INFO]      [exec]      from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
[INFO]      [exec]      from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
[INFO]      [exec]      from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
[INFO]      [exec]      from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:304:in `block in activate_bin_path'
[INFO]      [exec]      from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `synchronize'
[INFO]      [exec]      from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
[INFO]      [exec]      from /usr/local/bin/xcop:23:in `<main>'
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

How can I solve this?

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you help here?

**Comment by yegor256** [comment]
@volodya-lombrozo try `gem install xcop`. Then, `xcop --version`. Show the logs you are getting.

**Comment by yegor256** [comment]
@volodya-lombrozo you have two Rubies installed on your machine. One is inside `/System/Library/Frameworks/Ruby.framework/Versions/2.6` (old version) and another one (3.1.3) somewhere else, most probably installed by Homebrew. What does `which ruby` says? Where it leads?

**Comment by volodya-lombrozo** [comment]
@yegor256 `which ruby` said the following:
```
/Users/lombrozo/.rubies/ruby-3.1.3/bin/ruby
```

**Comment by yegor256** [comment]
@volodya-lombrozo apparently, `gem install xcop` installs `xcop` gem into `/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems` directory (check it). If this is the case, try to do `which gem`. Is it the one that belongs to Ruby 3.1.3?

**Comment by volodya-lombrozo** [comment]
@yegor256  
1) `which gem`:
```sh
➜  ~ which gem
/Users/lombrozo/.rubies/ruby-3.1.3/bin/gem
```
Seems it belongs to Ruby 3.1.3
2) Try to find `xcop` gem in `2.6`:
```sh
➜  ~ la /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0/gems | grep "xcop"  
➜  ~  
```
Nothing is found.
3) Try to find `xcop` gem in `3.1.3`:
```sh
➜  ~ echo $GEM_PATH                                               
/Users/lombrozo/.gem/ruby/3.1.3:/Users/lombrozo/.rubies/ruby-3.1.3/lib/ruby/gems/3.1.0
```
then 
```
➜  ~ la /Users/lombrozo/.gem/ruby/3.1.3/gems | grep "xcop"
drwxr-xr-x  21 lombrozo  staff   672B Jan 30 15:55 xcop-0.7.1
```

and
```
➜  ~ la /Users/lombrozo/.rubies/ruby-3.1.3/lib/ruby/gems/3.1.0/gems | grep "xcop"  
# nothing
```

**Comment by volodya-lombrozo** [comment]
It was the problem with xcop installation, actually I had several `xcop` installed on my machine:
```
➜  rubygems which -a xcop
/usr/local/bin/xcop
/Users/lombrozo/.gem/ruby/3.1.3/bin/xcop
/Users/lombrozo/.rubies/ruby-3.1.3/bin/xcop
/usr/local/bin/xcop
```

When I removed `/usr/local/bin/xcop` the problem was gone.
